# CodeRabbit configuration for fsuite
# See: https://docs.coderabbit.ai/reference/configuration
#
# Workflow:
#   1. Code & commit on a branch
#   2. Run `/coderabbit:review` locally (CLI) for quick iteration
#   3. Create PR — auto-review fires ONCE on PR creation (GitHub bot)
#   4. Fix findings, push — NO auto-review on subsequent pushes
#   5. Manually trigger `@coderabbitai review` on PR if you want another pass

language: "en-US"
tone_instructions: "Be direct and technical. Focus on security, correctness, and real bugs over style nitpicks. Skip praise — just flag issues."

reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_in_walkthrough: true
  collapse_walkthrough: false
  sequence_diagrams: true
  poem: false
  in_progress_fortune: false
  review_details: true
  enable_prompt_for_ai_agents: true

  auto_review:
    enabled: true                    # Auto-review on PR creation
    auto_incremental_review: false   # Do NOT re-review on every push
    drafts: false                    # Skip draft PRs
    ignore_title_keywords:
      - "WIP"
      - "DO NOT REVIEW"

  # Exclude local-only files and generated output from review
  path_filters:
    - "!CLAUDE.md"
    - "!AGENTS.md"
    - "!CLAUDE_AGENT_SDK_MIGRATION_MASTER_PLAN.md"
    - "!MEDIUM_*.md"
    - "!scripts/medium_*.py"
    - "!dist/**"
    - "!node_modules/**"
    - "!package-lock.json"

  # Path-specific review instructions
  path_instructions:
    - path: "fsearch"
      instructions: |
        Focus on: pattern normalization (glob/extension heuristics), backend selection
        (fd/fdfind vs find), and safe handling of user input (quoting, no word-splitting
        regressions). Prefer correctness and stability over micro-optimizations.
    - path: "fcontent"
      instructions: |
        Focus on: rg invocation safety (args handling), stdin file list handling,
        truncation accounting (SHOWN_MATCHES/TOTAL_FILES), and JSON/pretty output
        correctness. Avoid changes that could leak private paths in examples.
    - path: "ftree"
      instructions: |
        Focus on: timeout/budget behavior, excluded-directory handling, and correct
        recon output (counts/sizes/partial flags). Ensure graceful degradation when
        optional tools are missing.
    - path: "docs/**"
      instructions: |
        Check for: accurate CLI examples, no hardcoded personal paths or credentials,
        and clear explanations of flags and defaults.
    - path: "README.md"
      instructions: |
        Check for: accurate examples, correct filenames/paths, and no stale references.

  # Disable tools we don't need (not a Python/Go/Ruby/PHP project)
  tools:
    ruff:
      enabled: false
    phpstan:
      enabled: false
    phpmd:
      enabled: false
    phpcs:
      enabled: false
    golangci-lint:
      enabled: false
    rubocop:
      enabled: false
    swiftlint:
      enabled: false
    detekt:
      enabled: false
    flake8:
      enabled: false
    pylint:
      enabled: false
    clippy:
      enabled: false
    sqlfluff:
      enabled: false
    fortitudeLint:
      enabled: false
    checkov:
      enabled: false
    pmd:
      enabled: false
    clang:
      enabled: false
    cppcheck:
      enabled: false
    buf:
      enabled: false
    regal:
      enabled: false
    brakeman:
      enabled: false
    luacheck:
      enabled: false
    shopifyThemeCheck:
      enabled: false
    prismaLint:
      enabled: false
    circleci:
      enabled: false
    biome:
      enabled: false
    oxc:
      enabled: false
    # Keep enabled: shellcheck, markdownlint, gitleaks, htmlhint, yamllint,
    # hadolint, semgrep, actionlint

chat:
  auto_reply: true

knowledge_base:
  code_guidelines:
    enabled: true
    # CLAUDE.md and AGENTS.md are gitignored (local-only), so key guidance
    # is embedded in path_instructions above instead.
  learnings:
    scope: "local"
  web_search:
    enabled: true
